#deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-label-xyz
  name: my-deployment-name 
spec:
  replicas: 3
  selector:
    matchLabels:
     app: to-find-nodes-and-form-the-cluster
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate

  template:
    metadata:
      labels:
        app: to-find-nodes-and-form-the-cluster
        actorSystemName: betting-house 
    spec:
      serviceAccountName: my-cluster # check this name is right
      containers:
      - name: my-container-name
        image: franciscolopezsancho/betting-house:0.1.0-SNAPSHOT
        # Remove for a real project, the image is picked up locally for the integratio test
        imagePullPolicy: Always 
        #health
        livenessProbe:
          httpGet:
            path: /alive
            port: management
        readinessProbe:
          httpGet:
            path: /ready
            port: management
        #health
        ports:
        # akka-management bootstrap
        - name: management
          containerPort: 8558
          protocol: TCP
          # when contact-point-discovery.port-name is set for cluster bootstrap,
          # the management port must be named accordingly:
          # name: management
        - containerPort: 9000
        - containerPort: 9001
        - containerPort: 9002
        - containerPort: 9003
        env:
        # The Kubernetes API discovery will use this service name to look for
        # nodes with this value in the 'app' label.
        # This can be customized with the 'pod-label-selector' setting.
        - name: AKKA_CLUSTER_BOOTSTRAP_SERVICE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: "metadata.labels['app']"
        - name: JAVA_OPTS
          value: "-Xmx1024m -Ddockerized=true"  