kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]							#A
  verbs: ["get", "watch", "list"]					#B
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-pods
subjects:
- kind: ServiceAccount
  name: my-cluster								#C
roleRef:
  kind: Role
  name: pod-reader							#D
  apiGroup: rbac.authorization.k8s.io
